//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Airport
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationOfDiscounts
    {
        public int id_application_discounts { get; set; }
        public int id_ticket { get; set; }
        public int id_discount { get; set; }
    
        public virtual Box_Offic Box_Offic { get; set; }
        public virtual Discounts Discounts { get; set; }
    }
}
