//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Airport
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BaseDataEntities : DbContext
    {
        public BaseDataEntities()
            : base("name=BaseDataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ApplicationOfDiscounts> ApplicationOfDiscounts { get; set; }
        public virtual DbSet<Box_Offic> Box_Offic { get; set; }
        public virtual DbSet<Citys> Citys { get; set; }
        public virtual DbSet<Discounts> Discounts { get; set; }
        public virtual DbSet<Employees> Employees { get; set; }
        public virtual DbSet<EmployeesPhoto> EmployeesPhoto { get; set; }
        public virtual DbSet<Flights> Flights { get; set; }
        public virtual DbSet<Gender> Gender { get; set; }
        public virtual DbSet<Passengers> Passengers { get; set; }
        public virtual DbSet<Passport_deta> Passport_deta { get; set; }
        public virtual DbSet<Planes> Planes { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Routes> Routes { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
