//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Airport
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeesPhoto
    {
        public int id_photo { get; set; }
        public int id_employee { get; set; }
        public string photo_path { get; set; }
        public byte[] photo_binary { get; set; }
        public Nullable<bool> actual { get; set; }
    
        public virtual Employees Employees { get; set; }
    }
}
