//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Airport
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flights
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Flights()
        {
            this.Box_Offic = new HashSet<Box_Offic>();
        }
    
        public int id_flight { get; set; }
        public System.DateTime departure_date { get; set; }
        public System.TimeSpan departure_time { get; set; }
        public int id_route { get; set; }
        public int id_plane { get; set; }
        public double cost { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Box_Offic> Box_Offic { get; set; }
        public virtual Planes Planes { get; set; }
        public virtual Routes Routes { get; set; }
    }
}
