//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Airport
{
    using System;
    using System.Collections.Generic;
    
    public partial class Passport_deta
    {
        public int id_passport_deta { get; set; }
        public Nullable<int> series { get; set; }
        public Nullable<int> nomer { get; set; }
        public Nullable<System.DateTime> date_issue { get; set; }
        public string division_code { get; set; }
    
        public virtual Employees Employees { get; set; }
        public virtual Passengers Passengers { get; set; }
    }
}
